<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use LogicException;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (! app()->environment(['local', 'testing'])) {
            throw new LogicException('Demo accounts may only be seeded in local or testing environments.');
        }

        $users = [
            [
                'id' => 1,
                'name' => 'Dr. Aris Puji Widodo, S.Si., M.T.',
                'email' => 'arispujiw@admin.kampus.ac.id',
                'role' => 'admin',
                'account_type' => 'admin', 
                'identity_number' => '197404011999031002',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Annisa Istiadah N., A.Md',
                'email' => 'annisaisti@operator.kampus.ac.id',
                'role' => 'operator',
                'account_type' => 'petugas',
                'identity_number' => '198911012023102001',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Anang Ardiyanto, S.Kom.',
                'email' => 'anangardiyanto@operator.kampus.ac.id',
                'role' => 'operator',
                'account_type' => 'petugas',
                'identity_number' => '199406052023101001',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Ruth Septriana Sipangkar',
                'email' => 'ruthseptriana@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124120024',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Syafira Azka Ramadhani',
                'email' => 'syafirazka@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124130088',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Yasmina Syahidah',
                'email' => 'yasminasya@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124130116',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Muhammad Farhan Abdul Azis',
                'email' => 'mfarhanabdul@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140166',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Sandy Kurniawan, S.Kom., M.Kom.',
                'email' => 'sandykurniawan@lecturer.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'dosen',
                'identity_number' => '199603032024061003',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Henri Tantyoko, S.Kom., M.Kom.',
                'email' => 'henritantyoko@lecturer.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'dosen',
                'identity_number' => '199612272024061001',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Beny Nugroho, S.Kom.',
                'email' => 'benynugroho@staff.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'staf',
                'identity_number' => '198611152023101001',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],


            [
                'id' => 11,
                'name' => 'Harry Potter',
                'email' => 'harrypotter@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140167',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Hermione Granger',
                'email' => 'hermionegranger@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140168',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Ron Weasley',
                'email' => 'ronweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140169',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Ginny Weasley',
                'email' => 'ginnyweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140170',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Fred Weasley',
                'email' => 'fredweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140171',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'George Weasley',
                'email' => 'georgeweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140172',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Percy Weasley',
                'email' => 'percyweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140173',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Bill Weasley',
                'email' => 'billweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140174',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Charlie Weasley',
                'email' => 'charlieweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140175',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Arthur Weasley',
                'email' => 'arthurweasley@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140176',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Feanor',
                'email' => 'feanor@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140177',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Fingolfin',
                'email' => 'fingolfin@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140178',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Finarfin',
                'email' => 'finarfin@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140179',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Finrod Felagund',
                'email' => 'finrodfelagund@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140180',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Fingon',
                'email' => 'fingon@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140181',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Turgon',
                'email' => 'turgon@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140182',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Maedhros',
                'email' => 'maedhros@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140183',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Maglor',
                'email' => 'maglor@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140184',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Celegorm',
                'email' => 'celegorm@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140185',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Caranthir',
                'email' => 'caranthir@students.kampus.ac.id',
                'role' => 'user',
                'account_type' => 'mahasiswa',
                'identity_number' => '24060124140186',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
            ],


        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['id' => $user['id']],
                $user
            );
        }
    }
}
