@echo off

echo === Selamat datang ! ===

:: modul back-end
echo === Mengunduh vendor...
call composer install
echo === Membuat App Key...
php artisan key:generate
echo === Migrasi database...
php artisan migrate:fresh --seed
echo === Membersihkan semua cache...
php artisan optimize:clear

:: modul front-end
echo === Menginstall module frontend...
call npm install
echo === Mengunduh library Heroicon...
call npm install @heroicons/react

:: menjalankan backend dan frontend...
echo === Selesai! Menjalankan server frontend dan backend di terminal baru...
wt -d . cmd /k "php artisan serve" ; new-tab -d . cmd /k "npm run dev"