@echo off
echo Menyalin .env...
copy .env.example .env
echo Mengunduh vendor...
composer install
echo Membuat App Key...
php artisan key:generate
echo Migrasi database...
php artisan migrate
echo Selesai! Menjalankan server...
php artisan serve